# Generated by Django 4.1.6 on 2023-02-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductBrandName', models.CharField(max_length=30)),
                ('ProductBrandModel', models.CharField(max_length=20)),
                ('ProductBrandPrice', models.IntegerField()),
            ],
        ),
    ]
